-- Seed at least 35 AI tools with core metadata
-- Idempotent via ON CONFLICT (slug) DO UPDATE
-- Requires categories created by database-init.sql (optional, used via subquery)

BEGIN;

INSERT INTO tools (
  name, slug, tagline, description,
  pricing_model, status, website_url,
  api_available, open_source,
  platforms, supported_languages,
  primary_category_id,
  keywords, features, use_cases,
  published_at
) VALUES

-- 1. ChatGPT
('ChatGPT', 'chatgpt', 'Assistant conversationnel polyvalent',
 'Assistant IA conversationnel par OpenAI pour la rédaction, l’analyse et l’aide au quotidien.',
 'freemium', 'published', 'https://chat.openai.com/',
  true, false,
  '["web", "mobile"]'::jsonb, '["en", "fr", "es", "de"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Communication' LIMIT 1),
  '["chatbot", "assistant", "productivity"]'::jsonb,
  '["conversation", "reasoning", "summarization"]'::jsonb,
  '["support client", "rédaction", "apprentissage"]'::jsonb,
  NOW()),

-- 2. Claude
('Claude', 'claude', 'Assistant IA axé sur la sûreté et l’analyse',
 'Assistant d’Anthropic spécialisé dans la rédaction longue, l’analyse de documents et le code.',
 'freemium', 'published', 'https://claude.ai/',
  true, false,
  '["web"]'::jsonb, '["en", "fr", "es", "de"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Communication' LIMIT 1),
  '["assistant", "reasoning", "documents"]'::jsonb,
  '["analyse de PDF", "rédaction", "programmation"]'::jsonb,
  '["recherche", "rédaction marketing", "notes"]'::jsonb,
  NOW()),

-- 3. Google Gemini
('Google Gemini', 'google-gemini', 'Modèles multimodaux de Google',
 'Suite de modèles multimodaux (texte, image, audio, vidéo) pour la création et l’automatisation.',
 'freemium', 'published', 'https://ai.google.dev/gemini-api',
  true, false,
  '["web", "api"]'::jsonb, '["en", "fr", "es", "de"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Communication' LIMIT 1),
  '["multimodal", "api", "assistant"]'::jsonb,
  '["génération", "vision", "search"]'::jsonb,
  '["agents", "applications IA", "prototypage"]'::jsonb,
  NOW()),

-- 4. Microsoft Copilot
('Microsoft Copilot', 'microsoft-copilot', 'Assistant IA intégré à Microsoft 365',
 'Assistant IA pour Office, Windows et le web. Idéal pour la productivité et la rédaction.',
 'freemium', 'published', 'https://copilot.microsoft.com/',
  true, false,
  '["web", "desktop", "mobile"]'::jsonb, '["en", "fr", "es", "de"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Productivity' LIMIT 1),
  '["office", "productivity", "assistant"]'::jsonb,
  '["rédaction", "tableurs", "présentations"]'::jsonb,
  '["bureautique", "résumé", "idées"]'::jsonb,
  NOW()),

-- 5. Perplexity
('Perplexity', 'perplexity', 'Moteur de réponse IA avec citations',
 'Recherche et réponses augmentées par IA avec sources citées et suivi du contexte.',
 'freemium', 'published', 'https://www.perplexity.ai/',
  false, false,
  '["web", "mobile"]'::jsonb, '["en", "fr", "es", "de"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Communication' LIMIT 1),
  '["search", "qa", "assistant"]'::jsonb,
  '["recherche", "résumé", "exploration"]'::jsonb,
  '["veille", "apprentissage", "productivité"]'::jsonb,
  NOW()),

-- 6. Midjourney
('Midjourney', 'midjourney', 'Génération d’images créatives',
 'Plateforme populaire pour générer des images artistiques à partir de prompts texte.',
 'paid', 'published', 'https://www.midjourney.com/',
  false, false,
  '["web"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Design' LIMIT 1),
  '["image", "création", "art"]'::jsonb,
  '["génération d’images", "styles", "variations"]'::jsonb,
  '["illustration", "branding", "concept art"]'::jsonb,
  NOW()),

-- 7. DALL·E
('DALL·E', 'dalle', 'Génération d’images par OpenAI',
 'Génération et édition d’images à partir de texte, avec contrôle du style et des variations.',
 'paid', 'published', 'https://openai.com/research/dall-e',
  true, false,
  '["web", "api"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Design' LIMIT 1),
  '["image", "édition", "variation"]'::jsonb,
  '["génération", "inpainting", "outpainting"]'::jsonb,
  '["marketing visuel", "design produit", "idéation"]'::jsonb,
  NOW()),

-- 8. Stable Diffusion Web UI (AUTOMATIC1111)
('Stable Diffusion Web UI', 'stable-diffusion-webui', 'Interface locale pour Stable Diffusion',
 'Interface open source pour générer et affiner des images SD avec plugins et modèles.',
 'free', 'published', 'https://github.com/AUTOMATIC1111/stable-diffusion-webui',
  false, true,
  '["desktop", "self-hosted"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Design' LIMIT 1),
  '["open-source", "image", "local"]'::jsonb,
  '["txt2img", "img2img", "controlnet"]'::jsonb,
  '["création visuelle", "recherche", "prototypage"]'::jsonb,
  NOW()),

-- 9. Runway
('Runway', 'runway', 'Vidéo et image génératives',
 'Suite créative IA pour génération vidéo, retouche, et effets visuels.',
 'paid', 'published', 'https://runwayml.com/',
  true, false,
  '["web"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Design' LIMIT 1),
  '["video", "création", "édition"]'::jsonb,
  '["génération vidéo", "effets", "montage"]'::jsonb,
  '["pub", "contenu social", "cinéma"]'::jsonb,
  NOW()),

-- 10. Jasper
('Jasper', 'jasper', 'Rédaction marketing assistée',
 'Assistant de copywriting pour blogs, pubs et réseaux sociaux, avec modèles marketing.',
 'paid', 'published', 'https://www.jasper.ai/',
  true, false,
  '["web"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Marketing' LIMIT 1),
  '["copywriting", "marketing", "templates"]'::jsonb,
  '["blogs", "ads", "emails"]'::jsonb,
  '["SEO", "campagnes", "brand voice"]'::jsonb,
  NOW()),

-- 11. Copy.ai
('Copy.ai', 'copy-ai', 'Génération de textes marketing',
 'Outil IA pour générer des textes publicitaires, emails et contenus sociaux.',
 'freemium', 'published', 'https://www.copy.ai/',
  true, false,
  '["web"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Marketing' LIMIT 1),
  '["copywriting", "ads", "emails"]'::jsonb,
  '["contenu social", "landing pages", "emails"]'::jsonb,
  '["acquisition", "SEO", "growth"]'::jsonb,
  NOW()),

-- 12. Notion AI
('Notion AI', 'notion-ai', 'IA intégrée à Notion',
 'Fonctions IA dans Notion pour la rédaction, le résumé et la structuration de contenu.',
 'paid', 'published', 'https://www.notion.so/product/ai',
  false, false,
  '["web", "desktop", "mobile"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Productivity' LIMIT 1),
  '["notes", "rédaction", "résumé"]'::jsonb,
  '["docs", "wiki", "projets"]'::jsonb,
  '["organisation", "productivité", "idées"]'::jsonb,
  NOW()),

-- 13. GitHub Copilot
('GitHub Copilot', 'github-copilot', 'Assistant de code pour IDE',
 'Complétion de code basée sur IA dans VS Code, JetBrains et le web.',
 'paid', 'published', 'https://github.com/features/copilot',
  true, false,
  '["desktop", "ide"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["code", "autocomplete", "ide"]'::jsonb,
  '["programmation", "tests", "documentation"]'::jsonb,
  '["développement", "revue", "pairing"]'::jsonb,
  NOW()),

-- 14. Tabnine
('Tabnine', 'tabnine', 'Complétion IA pour le code',
 'Suggestions de code privées et option de déploiement self-hosted.',
 'paid', 'published', 'https://www.tabnine.com/',
  true, false,
  '["desktop", "ide", "self-hosted"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["autocomplete", "privacy", "on-prem"]'::jsonb,
  '["code", "unit tests", "refactoring"]'::jsonb,
  '["sécurité", "productivité dev"]'::jsonb,
  NOW()),

-- 15. Replit Ghostwriter
('Replit Ghostwriter', 'replit-ghostwriter', 'Assistant de code dans Replit',
 'Assistant IA intégré à Replit pour coder, expliquer et corriger.',
 'paid', 'published', 'https://replit.com/site/ghostwriter',
  true, false,
  '["web"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["code", "explanations", "chat"]'::jsonb,
  '["coding", "debug", "learn"]'::jsonb,
  '["éducation", "projets", "prototypage"]'::jsonb,
  NOW()),

-- 16. Hugging Face
('Hugging Face', 'hugging-face', 'Hub de modèles et datasets',
 'Plateforme open source pour modèles, datasets, Spaces et inference API.',
 'freemium', 'published', 'https://huggingface.co/',
  true, true,
  '["web", "api", "self-hosted"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["open-source", "models", "datasets"]'::jsonb,
  '["hébergement modèle", "inférence", "MLOps"]'::jsonb,
  '["recherche", "production", "démonstrations"]'::jsonb,
  NOW()),

-- 17. LangChain
('LangChain', 'langchain', 'Framework d’orchestration LLM',
 'Framework open source pour construire des applications LLM modulaires et agents.',
 'free', 'published', 'https://www.langchain.com/',
  false, true,
  '["library", "self-hosted"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["framework", "agents", "tools"]'::jsonb,
  '["RAG", "chaînes", "intégrations"]'::jsonb,
  '["prototypes", "apps IA", "agents"]'::jsonb,
  NOW()),

-- 18. Llama 3 (Meta)
('Llama 3', 'llama-3', 'Modèles LLM open source de Meta',
 'Famille de modèles LLM open source/weights pour divers cas d’usage.',
 'free', 'published', 'https://ai.meta.com/llama/',
  true, true,
  '["model", "self-hosted", "api"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["open-weights", "inference", "fine-tuning"]'::jsonb,
  '["génération", "chat", "code"]'::jsonb,
  '["recherche", "produit", "on-prem"]'::jsonb,
  NOW()),

-- 19. Mistral AI
('Mistral AI', 'mistral-ai', 'LLM européens et API',
 'Modèles légers et performants avec API et hébergement souverain.',
 'freemium', 'published', 'https://mistral.ai/',
  true, false,
  '["api", "model"]'::jsonb, '["en", "fr"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["LLM", "API", "souveraineté"]'::jsonb,
  '["chat", "RAG", "intégration"]'::jsonb,
  '["applis IA", "agents", "backend IA"]'::jsonb,
  NOW()),

-- 20. Cohere
('Cohere', 'cohere', 'LLM et embeddings pour entreprises',
 'API pour génération, classification et recherche sémantique à l’échelle.',
 'paid', 'published', 'https://cohere.com/',
  true, false,
  '["api"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["embeddings", "classify", "generate"]'::jsonb,
  '["RAG", "search", "NLP"]'::jsonb,
  '["entreprise", "prod", "analytics"]'::jsonb,
  NOW()),

-- 21. Anthropic API
('Anthropic API', 'anthropic-api', 'API pour modèles Claude',
 'Accès programmatique aux modèles Claude pour texte, outils et vision.',
 'freemium', 'published', 'https://docs.anthropic.com/',
  true, false,
  '["api"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["tools", "function-calling", "vision"]'::jsonb,
  '["agents", "automations", "chat"]'::jsonb,
  '["intégration", "backend IA", "RAG"]'::jsonb,
  NOW()),

-- 22. OpenAI API
('OpenAI API', 'openai-api', 'API pour GPT, DALL·E et plus',
 'API d’OpenAI pour génération de texte, image, audio et outils.',
 'paid', 'published', 'https://platform.openai.com/',
  true, false,
  '["api"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["gpt", "image", "realtime"]'::jsonb,
  '["chat", "vision", "speech"]'::jsonb,
  '["applications IA", "agents", "RAG"]'::jsonb,
  NOW()),

-- 23. ElevenLabs
('ElevenLabs', 'elevenlabs', 'Synthèse vocale réaliste',
 'Génération et clonage de voix avec haute qualité et API.',
 'paid', 'published', 'https://elevenlabs.io/',
  true, false,
  '["web", "api"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Communication' LIMIT 1),
  '["tts", "voice", "audio"]'::jsonb,
  '["voix off", "accessibilité", "jeux"]'::jsonb,
  '["podcast", "vidéo", "assistants vocaux"]'::jsonb,
  NOW()),

-- 24. Descript
('Descript', 'descript', 'Montage audio/vidéo assisté IA',
 'Édition par texte, suppression de bruits et doublage Overdub.',
 'freemium', 'published', 'https://www.descript.com/',
  true, false,
  '["desktop", "web"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Design' LIMIT 1),
  '["audio", "vidéo", "overdub"]'::jsonb,
  '["montage", "transcription", "nettoyage"]'::jsonb,
  '["créateurs", "formation", "marketing"]'::jsonb,
  NOW()),

-- 25. Synthesia
('Synthesia', 'synthesia', 'Vidéos avec avatars IA',
 'Création de vidéos avec avatars réalistes et voix multilingues.',
 'paid', 'published', 'https://www.synthesia.io/',
  true, false,
  '["web"]'::jsonb, '["en", "fr", "de", "es"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Design' LIMIT 1),
  '["avatar", "video", "studio"]'::jsonb,
  '["tutoriels", "RH", "marketing"]'::jsonb,
  '["formation", "présentations", "support"]'::jsonb,
  NOW()),

-- 26. Pika
('Pika', 'pika', 'Génération vidéo à partir de texte',
 'Génération et édition de clips vidéo courts via IA.',
 'freemium', 'published', 'https://pika.art/',
  false, false,
  '["web"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Design' LIMIT 1),
  '["video", "génération", "effets"]'::jsonb,
  '["teasers", "contenu social", "idéation"]'::jsonb,
  '["marketing", "créatif", "storyboard"]'::jsonb,
  NOW()),

-- 27. Luma AI
('Luma AI', 'luma-ai', 'Vidéo et 3D génératives',
 'Outils IA pour vidéo, NeRF et captures 3D réalistes.',
 'freemium', 'published', 'https://lumalabs.ai/',
  false, false,
  '["web", "mobile"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Design' LIMIT 1),
  '["3D", "video", "NeRF"]'::jsonb,
  '["captation", "modélisation", "rendu"]'::jsonb,
  '["jeux", "cinéma", "prod 3D"]'::jsonb,
  NOW()),

-- 28. Kapwing
('Kapwing', 'kapwing', 'Studio vidéo collaboratif',
 'Éditeur vidéo en ligne avec outils IA pour sous-titres et coupes.',
 'freemium', 'published', 'https://www.kapwing.com/',
  false, false,
  '["web"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Design' LIMIT 1),
  '["édition", "sous-titres", "redimension"]'::jsonb,
  '["création contenu", "social", "éducation"]'::jsonb,
  '["marketing", "création", "vidéo"]'::jsonb,
  NOW()),

-- 29. Canva Magic Design
('Canva Magic Design', 'canva-magic-design', 'Génération de designs assistée',
 'Fonctions IA de Canva pour créer des visuels et présentations rapidement.',
 'freemium', 'published', 'https://www.canva.com/features/ai/',
  false, false,
  '["web"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Design' LIMIT 1),
  '["templates", "image", "présentations"]'::jsonb,
  '["design", "branding", "réseaux sociaux"]'::jsonb,
  '["marketing", "productivité", "création"]'::jsonb,
  NOW()),

-- 30. Figma AI
('Figma AI', 'figma-ai', 'Fonctions IA pour Figma',
 'Outils IA intégrés à Figma pour accélérer la conception UI/UX.',
 'paid', 'published', 'https://www.figma.com/',
  false, false,
  '["desktop", "web"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Design' LIMIT 1),
  '["ui", "prototyping", "assist"]'::jsonb,
  '["maquettes", "composants", "contenu"]'::jsonb,
  '["design produit", "UI/UX", "collaboration"]'::jsonb,
  NOW()),

-- 31. Sora (OpenAI)
('Sora', 'sora', 'Génération vidéo réaliste',
 'Modèle de génération vidéo haute fidélité à partir de prompts texte.',
 'n/a', 'published', 'https://openai.com/research/video-generation-models',
  false, false,
  '["research"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Design' LIMIT 1),
  '["video", "génération", "recherche"]'::jsonb,
  '["cinématique", "storyboard", "concept"]'::jsonb,
  '["R&D", "création", "démonstrations"]'::jsonb,
  NOW()),

-- 32. OpenRouter
('OpenRouter', 'openrouter', 'Agrégateur d’API LLM',
 'Passerelle unifiée vers de multiples fournisseurs LLM avec routage et tarification.',
 'freemium', 'published', 'https://openrouter.ai/',
  true, false,
  '["api", "web"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["routing", "LLM", "tokens"]'::jsonb,
  '["intégration", "abstraction", "fallback"]'::jsonb,
  '["backend IA", "prototypage", "prod"]'::jsonb,
  NOW()),

-- 33. Pinecone
('Pinecone', 'pinecone', 'Base vectorielle managée',
 'Service vector database géré pour RAG, recherche sémantique et recommandation.',
 'paid', 'published', 'https://www.pinecone.io/',
  true, false,
  '["api", "cloud"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["vector-db", "index", "RAG"]'::jsonb,
  '["similarité", "recherche", "reco"]'::jsonb,
  '["prod", "scale", "low-latency"]'::jsonb,
  NOW()),

-- 34. Weaviate
('Weaviate', 'weaviate', 'Base vectorielle open source',
 'Vector DB open source avec modules et hébergement cloud.',
 'freemium', 'published', 'https://weaviate.io/',
  true, true,
  '["self-hosted", "cloud", "api"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["vector-db", "hybride", "modules"]'::jsonb,
  '["RAG", "semantic search", "ml"]'::jsonb,
  '["on-prem", "cloud", "plugins"]'::jsonb,
  NOW()),

-- 35. Qdrant
('Qdrant', 'qdrant', 'Vector DB haute performance',
 'Base vectorielle open source avec API gRPC/HTTP et filtres avancés.',
 'free', 'published', 'https://qdrant.tech/',
  true, true,
  '["self-hosted", "cloud", "api"]'::jsonb, '["en"]'::jsonb,
  (SELECT id FROM categories WHERE name = 'Development' LIMIT 1),
  '["vector-db", "filtering", "hybrid-search"]'::jsonb,
  '["RAG", "similarité", "recherche"]'::jsonb,
  '["on-prem", "edge", "scale"]'::jsonb,
  NOW())

ON CONFLICT (slug) DO UPDATE SET
  tagline = EXCLUDED.tagline,
  description = EXCLUDED.description,
  pricing_model = EXCLUDED.pricing_model,
  status = EXCLUDED.status,
  website_url = EXCLUDED.website_url,
  api_available = EXCLUDED.api_available,
  open_source = EXCLUDED.open_source,
  platforms = EXCLUDED.platforms,
  supported_languages = EXCLUDED.supported_languages,
  primary_category_id = EXCLUDED.primary_category_id,
  keywords = EXCLUDED.keywords,
  features = EXCLUDED.features,
  use_cases = EXCLUDED.use_cases,
  published_at = EXCLUDED.published_at,
  updated_at = NOW();

COMMIT;

